.circleci/config.yml, app/app/build.gradle
circleci is capable of signing the release apk on its own.
=> Circleci signing

app/app/src/main/java/com/github/livingwithhippos/unchained/base/MainActivity.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/settings/SettingsActivity.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/start/viewmodel/MainActivityViewModel.kt, app/app/src/main/res/values-it/strings.xml, app/app/src/main/res/values/strings.xml
Closes #25 
Back navigation from settings activity does not restore the previous state, kinda ugly, will fix later on.
=> Back bar button

app/app/src/main/java/com/github/livingwithhippos/unchained/downloaddetails/view/DownloadDetailsFragment.kt, app/app/src/main/res/drawable/icon_share.xml, app/app/src/main/res/menu/download_details_bar.xml, app/app/src/main/res/values-it/strings.xml, app/app/src/main/res/values/strings.xml
=> added share button to download details bar

app/app/src/debug/java/com/github/livingwithhippos/unchained/di/ApiFactory.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/authentication/view/AuthenticationFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/authentication/viewmodel/AuthenticationViewModel.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/base/MainActivity.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/model/APIError.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/model/Authentiication.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/model/NetworkResponse.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/remote/AuthApiHelper.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/remote/AuthApiHelperImpl.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/remote/AuthenticationApi.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/remote/DownloadApi.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/remote/TorrentsApi.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/remote/UnrestrictApi.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/remote/VariousApi.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/remote/VariousApiHelper.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/remote/VariousApiHelperImpl.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/repositoy/AuthenticationRepository.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/repositoy/BaseRepository.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/repositoy/UnrestrictRepository.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/repositoy/VariousApiRepository.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/newdownload/view/NewDownloadFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/start/viewmodel/MainActivityViewModel.kt, app/app/src/release/java/com/github/livingwithhippos/unchained/di/ApiFactory.kt
The token is correctly refreshed at launch and a refresh is scheduled before its expiration. Fixes #32
=> Refresh Token

app/app/src/main/java/com/github/livingwithhippos/unchained/base/DeleteDialogFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/downloaddetails/view/DownloadDetailsFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/lists/view/DownloadContextualDialogFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/lists/view/TorrentContextualDialogFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/torrentdetails/view/TorrentDetailsFragment.kt, app/app/src/main/res/layout/dialog_delete_confirmation.xml, app/app/src/main/res/layout/dialog_download_item.xml, app/app/src/main/res/layout/dialog_torrent_item.xml, app/app/src/main/res/values-it/strings.xml, app/app/src/main/res/values/strings.xml
=> Delete dialogs confirmations

app/app/schemas/com.github.livingwithhippos.unchained.data.local.UnchaineDB/1.json, app/app/schemas/com.github.livingwithhippos.unchained.data.local.UnchaineDB/2.json, app/app/src/main/java/com/github/livingwithhippos/unchained/base/MainActivity.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/base/UnchainedApplication.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/local/HostRegexDao.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/local/UnchaineDB.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/model/HostRegex.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/remote/HostsApi.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/remote/HostsApiHelper.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/remote/HostsApiHelperImpl.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/repositoy/HostsRepository.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/di/DatabaseModule.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/newdownload/view/NewDownloadFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/settings/SettingsFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/settings/SettingsViewmodel.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/start/viewmodel/MainActivityViewModel.kt, app/app/src/main/res/values-it/strings.xml, app/app/src/main/res/values/strings.xml, app/app/src/main/res/xml/settings.xml
You can now share hoster links with Unchained. It still has some issues:
1. The regexps are obtained from an api call, but they need to be converted
2. Some regexps do not match. Added a CUSTOM_REGEXPS field where I'll put new ones as errors are discovered
3. Sharing a link with an issue such as file unavailable will lock the interface (need to wait for #22)
Closes #20
=> Support shared hosting links

app/app/build.gradle, app/app/src/main/java/com/github/livingwithhippos/unchained/data/model/APIError.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/repositoy/BaseRepository.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/repositoy/UnrestrictRepository.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/newdownload/view/NewDownloadFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/newdownload/viewmodel/NewDownloadViewModel.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/utilities/extension/Extension.kt, app/app/src/main/res/layout/fragment_user_profile.xml, app/app/src/main/res/values-it/strings.xml, app/app/src/main/res/values/strings.xml
Used [Arrow's Either](https://arrow-kt.io/docs/apidocs/arrow-core-data/arrow.core/-either/) class. Still needs to be applied to every repository and network call.
Close #22
=> Manage api and network errors

app/app/src/main/java/com/github/livingwithhippos/unchained/data/remote/DownloadApi.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/repositoy/DownloadRepository.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/repositoy/TorrentsRepository.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/lists/model/DownloadPagingSource.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/lists/model/TorrentPagingSource.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/lists/view/ListsTabFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/lists/viewmodel/DownloadListViewModel.kt, app/app/src/main/res/drawable/icon_search.xml, app/app/src/main/res/menu/lists_bar.xml, app/app/src/main/res/values-it/strings.xml, app/app/src/main/res/values/strings.xml
=> Added search to download and torrent lists

app/app/src/main/res/values-it/strings.xml
Currently translated at 100.0% (220 of 220 strings)
Translation: Unchained for Android/strings
Translate-URL: https://localization.professiona.li/projects/unchained-for-android/strings/it/
=> Updated translation from Weblate

app/app/src/main/java/com/github/livingwithhippos/unchained/data/model/Stream.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/downloaddetails/view/DownloadDetailsFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/utilities/Constants.kt, app/app/src/main/res/drawable/icon_browser_stream.xml, app/app/src/main/res/layout-land/fragment_download_details.xml, app/app/src/main/res/layout/fragment_download_details.xml, app/app/src/main/res/values-fr/strings.xml, app/app/src/main/res/values-it/strings.xml, app/app/src/main/res/values/strings.xml
- added button to open a stream with the web player
- unified media list between alternatives and transcoded media
=> added open browser stream button

app/app/src/main/java/com/github/livingwithhippos/unchained/base/DeleteDialogFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/lists/view/ListsTabFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/lists/viewmodel/DownloadListViewModel.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/start/viewmodel/MainActivityViewModel.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/torrentdetails/view/TorrentDetailsFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/user/view/UserProfileFragment.kt, app/app/src/main/res/layout/fragment_folder_list.xml, app/app/src/main/res/menu/lists_bar.xml, app/app/src/main/res/values-fr/strings.xml, app/app/src/main/res/values-it/strings.xml, app/app/src/main/res/values/strings.xml
Added a button on the top menu of the list fragment to delete all the torrents/downloads
=> Delete all torrents/downloads option

app/app/src/main/java/com/github/livingwithhippos/unchained/base/MainActivity.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/downloaddetails/view/DownloadDetailsFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/folderlist/view/FolderListFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/lists/view/ListsTabFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/newdownload/view/NewDownloadFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/start/viewmodel/MainActivityViewModel.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/utilities/extension/Extension.kt, app/app/src/main/res/values-it/strings.xml
just some cleaning up for downloadmanager related stuff
=> Better download

app/app/build.gradle, app/app/src/main/java/com/github/livingwithhippos/unchained/base/MainActivity.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/repositoy/BaseRepository.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/repositoy/TorrentsRepository.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/repositoy/UnrestrictRepository.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/downloaddetails/view/DownloadDetailsFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/folderlist/view/FolderListFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/folderlist/viewmodel/FolderListViewModel.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/lists/view/ListsTabFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/lists/viewmodel/DownloadListViewModel.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/newdownload/view/NewDownloadFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/newdownload/viewmodel/NewDownloadViewModel.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/torrentdetails/viewmodel/TorrentDetailsViewModel.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/utilities/EitherResult.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/utilities/extension/Extension.kt
No point in using a whole library for a single utility class
=> Replaced Arrow's Either

app/app/build.gradle, app/app/src/debug/java/com/github/livingwithhippos/unchained/base/MainActivity.kt, app/app/src/debug/java/com/github/livingwithhippos/unchained/base/UnchainedApplication.kt, app/app/src/main/AndroidManifest.xml, app/app/src/main/java/com/github/livingwithhippos/unchained/authentication/view/AuthenticationFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/base/MainActivity.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/settings/view/SettingsFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/start/view/StartFragment.kt, app/app/src/main/res/values-fr/strings.xml, app/app/src/main/res/values-it/strings.xml, app/app/src/main/res/values/strings.xml, app/app/src/main/res/xml/settings.xml, app/app/src/release/java/com/github/livingwithhippos/unchained/base/MainActivity.kt
Since acra was crashing by itself I replaced it with [countly](https://count.ly/). I only tested it briefly but it seems to work well. It's installed in the debug version only anyway so there should be no problem
=> Replace acra with Countly

app/app/src/main/res/values-fr/strings.xml, app/app/src/main/res/values-it/strings.xml, app/app/src/main/res/values-tl/strings.xml
Permanent issue to keep the translation from Weblate updated
=> Translations

app/.run/Check dependencies updates.run.xml, app/app/src/main/java/com/github/livingwithhippos/unchained/data/repository/KodiRepository.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/di/ApiFactory.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/di/qualifiers.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/plugins/Parser.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/search/view/SearchFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/search/viewmodel/SearchViewModel.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/settings/view/SettingsFragment.kt, app/app/src/main/res/values-fr/strings.xml, app/app/src/main/res/values-it/strings.xml, app/app/src/main/res/values/strings.xml, app/app/src/main/res/xml/settings.xml
Now it should work. Tested with my mobile network and the zooqle/1337x plugins. Enabling DoH or changing DNSs manually or through a wifi network makes them work. Added a dialog to notify users of this feature.
close #156
=> Fix DNS over HTTPS

app/app/build.gradle, app/app/src/main/java/com/github/livingwithhippos/unchained/folderlist/view/FolderListFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/lists/view/ListsTabFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/user/view/UserProfileFragment.kt, app/app/src/main/res/layout/fragment_folder_list.xml, app/app/src/main/res/layout/fragment_search.xml, app/app/src/main/res/layout/fragment_tab_lists.xml, app/app/src/main/res/layout/fragment_user_profile.xml, app/app/src/main/res/values-fr/strings.xml, app/app/src/main/res/values-it/strings.xml, app/app/src/main/res/values/strings.xml, app/versions.gradle
Small fixes from 4.27.2
ready for google play
=> Merge dev for release 

extra_assets/plugins/nyaa.unchained
Thanks to LivingWithHippos for the assistance in making this.
=> Create nyaa.si plug-in

app/app/build.gradle, app/app/src/androidTest/java/com/github/livingwithhippos/unchained/base/CustomViewActions.kt, app/app/src/androidTest/java/com/github/livingwithhippos/unchained/base/MainActivityTest.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/start/viewmodel/MainActivityViewModel.kt, app/versions.gradle
-  added the test dependencies for future tests\
- updated target  sdk
=> Added some tests

app/app/src/main/java/com/github/livingwithhippos/unchained/downloaddetails/view/DownloadDetailsFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/downloaddetails/viewmodel/DownloadDetailsViewModel.kt, app/app/src/main/res/values-fr/strings.xml, app/app/src/main/res/values-it/strings.xml, app/app/src/main/res/values/arrays.xml, app/app/src/main/res/values/strings.xml, app/app/src/main/res/xml/settings.xml
- added support for custom media player to use for "send to media player"
- added web video cast as media player
=> Custom player

app/app/src/main/java/com/github/livingwithhippos/unchained/base/MainActivity.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/start/viewmodel/MainActivityViewModel.kt
should fix spinning login circle and app not working after bringing it back to front/ rotating the device
=> Fix activity restore

app/app/src/main/java/com/github/livingwithhippos/unchained/data/repository/DownloadRepository.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/repository/TorrentsRepository.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/repository/UnrestrictRepository.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/newdownload/view/NewDownloadFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/newdownload/viewmodel/NewDownloadViewModel.kt, app/app/src/main/res/values-fr/strings.xml, app/app/src/main/res/values-it/strings.xml, app/app/src/main/res/values/strings.xml
No messages are shown for adding downloads without premium
=> No premium

app/app/build.gradle, app/app/src/main/java/com/github/livingwithhippos/unchained/downloaddetails/view/DownloadDetailsFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/lists/view/ListsTabFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/lists/viewmodel/ListTabsViewModel.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/newdownload/view/NewDownloadFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/start/viewmodel/MainActivityViewModel.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/torrentdetails/view/TorrentDetailsFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/utilities/Constants.kt, app/app/src/main/res/layout/fragment_downloads_list.xml, app/app/src/main/res/layout/fragment_tab_lists.xml, app/app/src/main/res/layout/fragment_torrents_list.xml, app/app/src/main/res/menu/lists_bar.xml, app/app/src/main/res/values-fr/strings.xml, app/app/src/main/res/values-it/strings.xml, app/app/src/main/res/values/strings.xml, app/versions.gradle
use a viewpager2 instead of the current trick
close #195
=> Swipe between list tabs

app/app/src/main/java/com/github/livingwithhippos/unchained/authentication/view/AuthenticationFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/base/MainActivity.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/model/Updates.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/remote/UpdateApi.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/remote/UpdateApiHelperImpl.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/repository/UpdateRepository.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/di/ApiFactory.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/downloaddetails/view/DownloadDetailsFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/search/view/SearchFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/search/view/SearchItemFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/settings/view/SettingsFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/start/viewmodel/MainActivityViewModel.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/user/view/UserProfileFragment.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/utilities/Constants.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/utilities/extension/Extension.kt, app/app/src/main/res/values-fr/strings.xml, app/app/src/main/res/values-it/strings.xml, app/app/src/main/res/values/strings.xml
Updates are checked at startup. For every version the update message is shown only once. Fdroid, google play and github are supported
=> Updates check

app/app/src/main/java/com/github/livingwithhippos/unchained/torrentdetails/view/TorrentDetailsFragment.kt, app/app/src/main/res/menu/torrent_details_bar.xml, app/app/src/main/res/navigation/lists_nav_graph.xml, app/app/src/main/res/values-fr/strings.xml, app/app/src/main/res/values-it/strings.xml, app/app/src/main/res/values/strings.xml
useful for caching and such
close #261
=> added torrent file re-selection

app/app/build.gradle, app/app/src/main/java/com/github/livingwithhippos/unchained/base/MainActivity.kt, app/app/src/main/res/menu/top_app_bar.xml, app/app/src/main/res/values-fr/strings.xml, app/app/src/main/res/values-it/strings.xml, app/app/src/main/res/values/strings.xml, app/build.gradle, app/versions.gradle
Added an "About" screen with app information and library licenses.
=> feat: Added about page

.github/workflows/build.yaml
=> updated github actions

app/app/src/main/java/com/github/livingwithhippos/unchained/data/model/DownloadItem.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/model/TorrentItem.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/data/model/cache/InstantAvailability.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/plugins/model/Plugin.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/plugins/model/ScrapedItem.kt, app/app/src/main/java/com/github/livingwithhippos/unchained/settings/viewmodel/KodiManagementViewModel.kt
=> Use kotlin plugin for parcelable classes

app/app/src/main/res/values-es/strings.xml, app/app/src/main/res/values-fr/strings.xml, app/app/src/main/res/values-it/strings.xml
android may have changed something because these used to work. Close #332
=> added plurals options
